language: node_js

sudo: false

matrix:
  include:
    - node_js: node
      script:
        - npm run-script test-with-coverage

node_js:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

